"""add mcp_active_collection

Revision ID: 22e7af0c1f0b
Revises: cb99812f0745
Create Date: 2026-08-17 00:53:00.870225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e7af0c1f0b'
down_revision: Union[str, Sequence[str], None] = 'cb99812f0745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_active_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO mcp_active_collection (id, collection_id) VALUES (1, NULL)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_active_collection')
    # ### end Alembic commands ###
